### ISSUE TITLE
Stop the wave when the file is ended and not with timer

### ISSUE THREAD

**Issue by Groovit** [sdesalve/hassio-addons#13]
Hi, is it possible to stop automatically the call when the Wav file is ended and not with the setting Call_duration ?
Thanks

**Comment by sdesalve** [comment]
no, I'm sorry.

**pjsua** command is interactive and don't let me know call status during script execution

**Comment by Groovit** [comment]
Ok
It's pitty
Thanks

**Comment by sdesalve** [comment]
You can add (with sox options) an empty wav file... But plaing is not synced with attendee phone answer

**Comment by sgtchains** [comment]
I haven't tried it, but perhaps adding '--auto_play_hangup' to 'pjsua_custom_options' in the config.  As for what the issue author is attempting to do with the calls, I have no idea.  Perhaps the remote auto-answers.

**Comment by sdesalve** [comment]
I can't find this option in Pjsua man page:

https://www.pjsip.org/pjsua.htm#cmdline

Where is documented?

**Comment by sgtchains** [comment]
I saw it as output from --help on a recently compiled pjsua

**Comment by sgtchains** [comment]
Actually, I think I have figured out a bash way to do this.  Please bear with me, and if I'm being a pest, then please let me know.

Wave file duration can be compared against '$MAX_CALL_TIME_VALUE' using soxi (which I assume is installed with sox) and whichever is shorter is used for the sleep value;

$(soxi -d  /share/dss_voip/dss_message_tts.wav | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }') 

As that output can be a float, the bc package would need to be installed, I'm assuming that it already is.

if [ $(echo "$(soxi -d  share/dss_voip/dss_message_tts.wav | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }') < $MAX_CALL_TIME_VALUE" | bc) -eq 1 ]; then
   MAX_CALL_TIME_VALUE=$(soxi -d  share/dss_voip/dss_message_tts.wav | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3 }')
fi

I'm guessing that you'd want a flag in the configuration for the new behavior.

.. again, let me know if I'm being a pest.

**Comment by sdesalve** [comment]
So with this command it will check for wav time length and, if it was smaller than MAX_CALL_TIME_VALUE, it set call duration to wav file length, I've correctly understood?

I think the primary issue is that with bash and pjsua I can't get call status and pjsua will stay in interactive mode until sleep timer will run out...

I'm fearing that next step should be to rewrite all add-on and use AppDaemon and pjsip python's API

But it will be on a far far future

**Comment by sgtchains** [comment]
Yes, you are correct about MAX_CALL_TIME_VALUE and wav length.

If you want I should be able to code this up in a day, and put it into a pull request.  Would you be interested in that?

**Comment by sdesalve** [comment]
Yes, you can.

But you must check that all new commands are available and, if not available, they must be added to container.

Please change your explained logic:

If in add-on configuration (or on add-on invoke) MAX_CALL_TIME_VALUE is set to "-1" use wav length... Otherwise let max call time and existing logic...

(I'm fearing that you will not earing nothing because wav file will start before you pickup phone and answer to call... Please check add-on functionality before the pull request!)

**Comment by sgtchains** [comment]
Sent pull request last night.  As for your concerns that I will hear silence because the wav will have finished playing before I answer the call, this will be used for the local PBX's intercom.  It auto-answers and pages all phones, and all I really need is ~ 250ms of silence added to the start of the wav file.  I am trying to avoid a number of issues with long calls; 1) intercom holding phones open, forcing users to hang up on the intercom to place call.  2) intercom messages queuing on the PBX because another message is being played.  3) Obnoxiously long messages being played because of 'auto-loop'
