### ISSUE TITLE
Hi Salvatore, To report you that the ADDON cannot be installed

### ISSUE THREAD

**Issue by Ejeb59** [sdesalve/hassio-addons#83]
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 17:01:54 (6 occurrences)
Last logged: 17:42:13

Failed to to call /addons/89275b70_dss_voipARM/install - '89275b70_dss_voipARM'
Failed to to call /store/addons/89275b70_dss_voipARM - Addon 89275b70_dss_voipARM with version latest does not exist in the store

**Comment by jarlesb** [comment]
Any news on this one? Got the same error...

**Comment by sdesalve** [comment]
please give me more info about your hassio setup. It's Hassio that cannot get correctly addon files

**Comment by jarlesb** [comment]
Hi Salvatore, 
And thanks for reply! I am running Hassio on Home assistant blue. 

- core 2023.11.2
- supervisor 2023.11.3
- os 11.1

Error when clicking install is:
Could not install addon
89275b70_dss_voipARM

Best regards, 
Jarle

**Comment by sdesalve** [comment]
> Could not install addon
> 89275b70_dss_voipARM

Seems that your hassio cannot download from GitHub. 
Try to download add-on folder from your computer and put in /addon folder on your hassio root and install from local

**Comment by jarlesb** [comment]
The following error comes after I copied the /dss_voipARM folder to addons/dss_voipARM:

2023-11-15 22:19:54.892 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/local_dss_voipARM/install - 'local_dss_voipARM'

Was it copied to correct folder?

I am located in Norway, and with fiber connection and the dss_voip addons installed without problems. But I cannot get that to work and since I have the Home Assistant Blue, then I should rather use the ARM one, correct?

Thanks & best regards

**Comment by jarlesb** [comment]
I earlier had the dss_voip34 version installed and this worked well some time ago...

**Comment by sdesalve** [comment]
Updated. Now should work

**Comment by Henry1959** [comment]
Thankyou Salvatore
